export const PAGES_ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/signup",
  PROFILE: "/profile",
  PROFILE_WITH_ID: "/profile/:userId",
  SUMMARY: "/summary",
  QUIZ: "/quiz",
  GENERATE_LESSON: "/generate-lesson",
  LESSONS_LIST: "/lesson",
  LESSON: "/lesson/*",
  FRIENDS: "/friends",
  NOTIFICATIONS: "/notifications",
  SETTINGS: "/settings",
};
